/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ArtworkRequestModel } from './artworkRequest';


export interface ArtistRequestModel {
    biography: string; 
    id?: number;
    name?: string;
    nationality?: string;
    dateOfBirth?: number;
    dateOfDeath?: number;
    artworks?: Array<ArtworkRequestModel>;
}

