/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReviewModel } from './review';


export interface ArtworkModel { 
    id?: number;
    title?: string;
    creationYear?: number;
    description?: string;
    averageRating?: number;
    reviews?: Array<ReviewModel>;
}

