/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReviewRequestModel } from './reviewRequest';


export interface ArtworkRequestModel { 
    id?: number;
    title?: string;
    creationYear?: number;
    description?: string;
    averageRating?: number;
    artist?: string;
    museum?: string;
    reviews?: Array<ReviewRequestModel>;
    favorite?: boolean;
}

