/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AuthResponseModel { 
    status?: AuthResponseModel.StatusEnum;
    message?: string;
    error?: boolean;
}
export namespace AuthResponseModel {
    export const StatusEnum = {
        Success: 'SUCCESS',
        Failure: 'FAILURE'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


