/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ArtworkRequestModel } from './artworkRequest';


export interface MuseumRequestModel { 
    id?: number;
    name?: string;
    location?: string;
    description?: string;
    founded?: number;
    artworks?: Array<ArtworkRequestModel>;
}

