/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SortObjectModel } from './sortObject';


export interface PageableObjectModel { 
    offset?: number;
    sort?: Array<SortObjectModel>;
    pageSize?: number;
    paged?: boolean;
    pageNumber?: number;
    unpaged?: boolean;
}

