/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SortObjectModel } from './sortObject';
import { PageableObjectModel } from './pageableObject';
import { UserSummaryResponseModel } from './userSummaryResponse';


export interface PageUserSummaryResponseModel { 
    totalElements?: number;
    totalPages?: number;
    first?: boolean;
    last?: boolean;
    numberOfElements?: number;
    size?: number;
    content?: Array<UserSummaryResponseModel>;
    number?: number;
    sort?: Array<SortObjectModel>;
    pageable?: PageableObjectModel;
    empty?: boolean;
}

