/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserStatsResponseModel { 
    name?: string;
    starsData?: { [key: string]: number; };
    following?: number;
    followers?: number;
    avgGiven?: number;
    numReviews?: number;
    top10favByArtist?: { [key: string]: number; };
    top10Artists?: { [key: string]: number; };
}

