/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReviewModel } from './review';
import { ArtworkModel } from './artwork';


export interface UserModel { 
    id?: number;
    name?: string;
    email?: string;
    password?: string;
    biography?: string;
    location?: string;
    roles?: Array<string>;
    createdAt?: string;
    reviews?: Array<ReviewModel>;
    following?: Set<UserModel>;
    followers?: Set<UserModel>;
    favoriteArtworks?: Set<ArtworkModel>;
}

