/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReviewRequestModel } from './reviewRequest';


export interface UserReviewsResponseModel { 
    currentPage?: number;
    previousPage?: number;
    nextPage?: number;
    totalReviews?: number;
    totalPages?: number;
    range?: string;
    reviews?: Array<ReviewRequestModel>;
}

