name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Grant execute permission for Maven
      run: chmod +x ./mvnw

    - name: Build JAR
      working-directory: backend
      run: ./mvnw clean package -DskipTests

    - name: Copy JAR to Docker context
      run: cp backend/target/Arteum-0.0.1-SNAPSHOT.jar docker/

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/arteum-app:latest docker/
        docker push ${{ secrets.DOCKER_USERNAME }}/arteum-app:latest
