name: Run Tests on Pull Request

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      BASE_URL: "https://localhost:8080"

    defaults:
      run:
        working-directory: backend
    
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: arteum
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip xvfb
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install -y ./google-chrome-stable_current_amd64.deb

    - name: Build and start backend
      run: |
        mvn clean package -DskipTests
        # Arrancamos la app en el puerto 8080 (HTTP) para los UI tests
        java -Dserver.port=8080 \
             -Dspring.profiles.active=test \
             -jar target/Arteum-0.0.1-SNAPSHOT.jar & 
        sleep 20

    - name: Grant execute permission for Maven
      run: chmod +x ./mvnw

    - name: Run Tests
      run: |
        ./mvnw test \
          -Dbase.url=${{ env.BASE_URL }} \
          -e -X
